# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybillboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(verbose_name='comment_date')),
                ('comment_message', models.CharField(max_length=400)),
                ('comment_user', models.CharField(max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybillboard.Post')),
            ],
        ),
    ]
